# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    #goals: 'clean compile test jacoco:report dependency-check:check'
    goals: 'clean compile test jacoco:report'


- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Unit test reports'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '**/site/jacoco/jacoco.xml'
    pathToSources: '**/src/main/'
    reportDirectory: '**/site/jacoco/'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonarcloud-AzureDevOps'
    organization: 'msrinivascharan'
    scannerMode: 'CLI'
    configMode: 'file'
    cliProjectKey: 
- task: SonarCloudAnalyze@1

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'war:war'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false


- task: JMeterInstaller@0
  inputs:
    jmeterVersion: '5.2.1'

- task: TaurusInstaller@0
  inputs:
    taurusVersion: '1.14.1'
    pythonCommand: 'python3'

- task: TaurusRunner@0
  inputs:
    jmeterHome: '$(JMeterInstaller.JMeterHome)'
    jmeterPath: '$(JMeterInstaller.JMeterPath)'
    jmeterVersion: '$(JMeterInstaller.JMeterVersion)'
    outputDir: 'taurus-output'